import numpy as np
from numpy import random
import math
import matplotlib.pyplot as plt
import itertools
import pandas as pd
import os
import sys
from scipy.signal import welch

def plot_isi(spike_train):
    isi = []
    for i in range(len(spike_train)-1):
        isi.append(spike_train[i+1]-spike_train[i])
    
    plt.figure()
    plt.hist(isi, color="teal", edgecolor='black')
    
    plt.title("Interspike interval distribution", fontweight='bold', fontsize=16)
    plt.xlabel("Interval [ms]")
    plt.ylabel("Count")

def plot_layout(ax, loc="lower left"):
    """Sets up layout given the axis of a plot. generated by chatGPT and modified"""
    ax.set_facecolor("#F5F5F5")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color("#333333")
    ax.spines["bottom"].set_color("#333333")
    ax.xaxis.label.set_color("#006D5B")
    ax.yaxis.label.set_color("#006D5B")
    ax.tick_params(axis='both', colors="#333333", labelsize='large' )
    ax.grid(color='#B0B0B0', linestyle='-', linewidth=0.5)
    ax.legend(facecolor="white", edgecolor="#333333", loc=loc)


def calculate_noise(tau_si, C_m_si, Vm_SD, delta):
    """Computes and returns the noise level given:
    tau_si : membrane time constant in SI-units
    C_m : membrane capacitance in SI-units
    Vm_SD : standard deviation of membrane potential
    delta : rate of change of current (how often new samples are drawn from Gaussian dist)"""
    
    SD_si = math.sqrt( (2 * C_m_si**2 * Vm_SD**2) / (delta * tau_si ))
    SD = SD_si / (1e-12)
    
    return SD

def transfer_V_to_I(V_target_si, f, tau_si=10e-3, R_si=100e6, E_m_si=-60e-3):
    """Transfers a target membrane potential to the stimulating current 
    necessary to give this membrane potential during simulation
    V_target_si : Targeted membrane potential
    f : input frequency
    tau_si : membrane time constant in SI-units
    R_si : membrane resistance in SI-units
    E_m_si: resting potential in SI-units"""
    
    a_si = (-E_m_si+V_target_si) * math.sqrt(1 + (2*math.pi*f*tau_si)**2) / R_si
    a = a_si/(1e-12)
    
    return a


def save_figure1(filename):
    """Saves figures to the results-folder given a filename"""
    Path = os.getcwd()
    sys.path.append(Path)
    save_dir = os.path.join(os.getcwd(), "results")
    os.makedirs(save_dir, exist_ok=True)
    file_index = 1
    while os.path.exists(os.path.join(save_dir, f"main_{file_index}.png")):
        file_index += 1
    
    save_path = os.path.join(save_dir, f"{filename}_{file_index}.png")
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
 
    print(f"Saved plot as: {save_path}")
    
def save_figure(fig, filename):
    """Saves the given matplotlib figure to the results-folder given a filename"""
    save_dir = os.path.join(os.getcwd(), "results")
    os.makedirs(save_dir, exist_ok=True)
    file_index = 1
    while os.path.exists(os.path.join(save_dir, f"{filename}_{file_index}.png")):
        file_index += 1
    
    save_path = os.path.join(save_dir, f"{filename}_{file_index}.png")
    fig.savefig(save_path, dpi=300, bbox_inches="tight")
    print(f"Saved plot as: {save_path}")


def find_spike_rate(spike_times, bin_size, sim_time, demean):
    #creating bins with width = bin_size (ms)
    t_bins = np.arange(0, sim_time + bin_size, bin_size)
    
    # putting spike train into the bins 
    spike_counts, _ = np.histogram(spike_times, bins=t_bins)
    
    # Spike rate
    spike_rate = spike_counts / (bin_size / 1000.0)

    if demean:
        spike_rate = spike_rate - spike_rate.mean()

    return spike_rate, spike_counts


def psd(spike_times, bin_size, sim_time, f, demean=False, normalize=False):
    spike_rate, _ = find_spike_rate(spike_times, bin_size, sim_time, demean=demean)
    
    dt = bin_size / 1000
    fs = 1 / dt
    
    fft_vals = np.fft.rfft(spike_rate)
    psd = (np.abs(fft_vals) ** 2) * dt  # viktig: squared

    
    freqs = np.fft.rfftfreq(len(spike_rate), d=dt)

    # # Cut off high-frequency tail to avoid artifacts near Nyquist
    mask = freqs < f + 800
    freqs = freqs[mask]
    psd = psd[mask]

    if normalize:
        psd = psd / np.max(psd)
    
    return freqs, psd

def psd_welch(spike_times, sim_time, bin_size=0.25, segments=16, f=1000, demean=False, normalize=False):
    """Computes the PSD of spiketrain given:
    spike_times : spike train, 
    sim_time : duration of simulation
    bin_size : frequency resolution
    segments : number of segments the signal is to be divided into
    It returns PSD-values of the spike train, and corresponding frequencies"""
    spike_rate, spike_counts = find_spike_rate(spike_times, bin_size, sim_time, demean)
    # Sampling rate (measurements per sec)
    fs = 1000 / bin_size 
    
    # using scipys Welch function to find frequencies and psd values. overlap fraction is 0.5 
    # This function splits the signal into overlapping segments, computes PSD for each segment and averages
    freqs, psd_values = welch(spike_rate, fs=fs, nperseg=len(spike_counts)//segments,
                              noverlap=(len(spike_counts)//segments)//2)
    
    if normalize:
        psd_values = psd_values / np.max(psd_values)
    

    # Cut off high-frequency tail to avoid artifacts near Nyquist
    mask = freqs < f + 800
    freqs = freqs[mask]
    psd = psd_values[mask]
    

    return freqs, psd


def autocorr(spike_times, bin_size, sim_time, normalize=False, demean=False):
    spike_rate, spike_counts = find_spike_rate(spike_times, bin_size, sim_time, demean)
    x = np.asarray(spike_rate, dtype=float)

    M = len(x)
    r = np.correlate(x, x, mode="full")   # length 2M - 1

    if normalize:
        lags = np.arange(-M + 1, M)       # same length as r
        r = r / (M - np.abs(lags))        # unbiased normalization 

    return r, spike_counts

def psd_autocorr(spike_times, bin_size, sim_time, f=1000, normalize=False, demean=False):

    spike_rate, spike_counts = autocorr(spike_times, bin_size, sim_time, normalize=normalize, demean=demean)
    dt = bin_size / 1000  # seconds
    print("dt", dt)
    fs = 1000 / bin_size
    print("fs:", fs)

    # reorganizes the structure of spike_rate array
    r_shifted = np.fft.ifftshift(spike_rate)
    #psd = np.real(np.fft.rfft(r_shifted)) * dt
    # FFT of autocorrelation
    psd = np.maximum(np.real(np.fft.rfft(r_shifted)) * dt, 0)
    freqs = np.fft.rfftfreq(len(spike_rate), d=dt)
    #psd = (np.abs(fft) ) * dt 

    # avoid artifacts near Nyquist
    mask = freqs < f + 800
    freqs = freqs[mask]
    psd = psd[mask]

      
    if normalize:
        psd = psd / np.max(psd)

    return freqs, psd


def welch_autocorr(spike_times, bin_size, sim_time, segments=16, f=1000, demean=False, normalize=False):
    """This function finds the spike rate from the spike train to make a continuous array,
    and divides the array in overlapping segments, applies a hanning window function to avoid artifacts, 
    and takes the FFT of the autocorrelation of each segment and then takes the average 
    over all segments to find a Welch-likefourier transform of the autocorrelation"""

    spike_rate, _ = find_spike_rate(spike_times, bin_size, sim_time, demean=demean) # to make continuous signal

    x = np.asarray(spike_rate, dtype=float)
    N = len(x) # number of datapoints
    seg_len = N // segments # length of each segment

    step = seg_len // 2   # 50% overlap
    dt = bin_size / 1000.0 # seconds

    win = np.hanning(seg_len) # hanning window
    fft_segments = []

    for start in range(0, N - seg_len + 1, step): 
        seg = x[start:start + seg_len].copy() 

        # demean based on each segment 
        if demean:
            seg = seg - np.mean(seg) 

        # multiply the segment with the hanning window
        seg = seg * win 

        # autocorrelation
        r = np.correlate(seg, seg, mode="full") / seg_len

        r_shifted = np.fft.ifftshift(r) # rearrange the order of the signal

        fft_seg = np.real(np.fft.rfft(r_shifted)) * dt # fft
        fft_seg = np.maximum(fft_seg, 0) # remove negative values if any

        fft_segments.append(fft_seg)

    if len(fft_segments) == 0:
        return np.array([]), np.array([])

    min_len = min(len(p) for p in fft_segments) # finding shortest fft length
    fft_segments = np.array([p[:min_len] for p in fft_segments]) 
    fft = np.mean(fft_segments, axis=0)

    freqs = np.fft.rfftfreq(2 * seg_len - 1, d=dt)[:min_len]

    mask = freqs < f + 800

    if normalize:
        fft = fft / np.max(fft)
    return freqs[mask], fft[mask]

def psd_Vm(Vm, sim_time, resolution, segments=16, f=1000):
    """Computes the PSD-values of the membrane potential given:
    Vm : recorded membrane potential, 
    sim_time : duration of simulation
    bin_size : frequency resolution
    segments : number of segments the signal is to be divided into
    It returns PSD-values of the membrane potential, and corresponding frequencies"""
    
    fs = 1000.0 / resolution  # Sampling frequency [Hz]
    
    # using scipys Welch function to find frequencies and psd values. overlap fraction is 0.5 
    freqs, psd_values = welch(Vm, fs=fs, nperseg=len(Vm)//segments, noverlap=(len(Vm)//segments)//2)
    
    freqs = freqs[freqs<f+800]
    psd_values = psd_values[:len(freqs)]

    return freqs, psd_values

def autocorr_vm(Vm, normalize=False, demean=False):
    Vm = np.asarray(Vm, dtype=float)

    if demean:
        Vm = Vm - np.mean(Vm)

    r = np.correlate(Vm, Vm, mode="full")
    r = r[r.size // 2:]   # behold bare ikke-negative lag

    if normalize and r[0] != 0:
        r = r / r[0]

    return r

def psd_Vm_autocorr(Vm, sim_time, bin_size, resolution=0.25, f=1000):
    r = autocorr_vm(Vm, normalize=False, demean=True)

    dt = resolution / 1000.0
    psd = np.abs(np.fft.rfft(r)) * dt
    freqs = np.fft.rfftfreq(len(r), d=dt)

    keep = freqs < f + 800
    freqs = freqs[keep]
    psd = psd[keep]

    return freqs, psd






def simulated_SNR(Vm, a, psd_values,
                f, freqs, arg_f, sim_time,
                sd, beat, spike_times, 
                second_sine, 
                auto_freqs=None,
                auto_values=None):
    """This function calculates the SNR. It also creates and returns dataframe to display SNR and other data,
    providing functionality and control throughout simulations
    Vm : Recorded membrane potential
    a: amplitude of input current
    psd_values: PSD of spike-train
    f : frequency of input current 
    freqs : list of frequencies corresponding to PSD-values
    arg_f : argument in freqs closest to input frequency
    sim_time : duration of simulation
    sd : noise level (standard deviation of current)
    beat : modulation frequency
    spike_times : list of times when action pot. is recorded
    second_sine : whether or not the second AC-generator is connected"""
    
    window = 5  # 5 Hz-window around f

    # Finding the indexes of frequencies around the input frequency
    noise_mask = (freqs >= freqs[arg_f] - window) & (freqs <= freqs[arg_f] + window) & (freqs != freqs[arg_f])
    
    max_fft_value = np.max(np.abs(psd_values))
    fft_value_f = np.abs(psd_values[arg_f])
    max_freq = freqs[np.argmax(np.abs(psd_values))]

    # Local noise average 
    noise_avg = np.mean(psd_values[noise_mask])
    
    SNR = compute_SNR(freqs, psd_values, f)
    
    results_list = []


    # Creating dictionary to return results, separating between one and two AC-generators
    if second_sine:
        
        SNR_beat = compute_SNR(freqs, psd_values, beat)
        arg_beat = np.argmin(freqs-beat)
        noise_mask = (freqs >= freqs[arg_f] - window) & (freqs <= freqs[arg_f] + window) & (freqs != freqs[arg_f])
        noise_avg_beat = np.mean(psd_values[noise_mask])
        results_list.append({
        "Input Frequency (Hz)": [f, f+beat],
        "Beat Frequency (Hz)": beat,
        "Current Amplitude (pA)": a,
        "Max Vm (mV)": np.max(Vm),
        "SD Vm (mV)": np.std(Vm),
        "Max FFT Amplitude [(spikes per sec)/Hz]": np.round(max_fft_value,2),
        "PSD Amplitude for f [(spikes pr sec)/Hz]": round(fft_value_f,2),
        "PSD Amplitude for f2-f1 [(spikes pr sec)/Hz]": round(psd_values[arg_beat],2),
        "Frequency at max (Hz)": max_freq,
        "SNR (f)": round(SNR,2),
        "noise average": round(noise_avg,2),
        "Spike Rate (spikes/s)": (len(spike_times)/sim_time)*1000,
        "SNR (beat)": round(SNR_beat,1),
        "noise average (beat)" : round(noise_avg_beat,1),
        
        
    })
    else:
        results_list.append({
        "Input Frequency (Hz)": f,
        "Current Amplitude (pA)": a,
        "Max Vm (mV)": np.max(Vm),
        "SD Vm (mV)": np.std(Vm),
        "Max PSD Amplitude [(spikes per sec)/Hz]": round(max_fft_value,2),
        "PSD Amplitude for f [(spikes pr sec)/Hz]": round(fft_value_f,2),
        "Frequency at max (Hz)": max_freq,
        "SNR": round(SNR,2),
        "noise average": round(noise_avg,2),
        "Spike Rate (spikes/s)": (len(spike_times)/sim_time)*1000
            
    })

    if auto_values is not None:
        print("entered block")
        SNR_auto = compute_SNR(auto_freqs, auto_values, f)
        if second_sine:
            SNR_auto = compute_SNR(auto_freqs, auto_values, beat)
        #SNR_auto_vm = compute_SNR(auto_freqs_vm, auto_values_vm, f)
        results_list[0]["SNR (autocorr)"] = SNR_auto
        index = np.argmax(auto_values)
        results_list[0]["f at max (autocorr)"] = auto_freqs[index]
        
    # returning dictionary as dataframe to display data
    return pd.DataFrame(results_list), noise_avg


def compute_SNR(freqs, psd_values, f):
    """Computes and returns SNR given PSD_values and corresponding frequencies."""
    
    window = 5  # 5 Hz-window around f
    
    # Frequency closest to f 
    arg_f = np.argmin(np.abs(freqs-f))
    print("arg_f:", arg_f)
    # Finding the indexes of frequencies around the input frequency
    noise_mask = (freqs >= freqs[arg_f] - window) & (freqs <= freqs[arg_f] + window) & (freqs != freqs[arg_f])
    

    # Local noise average 
    noise_avg = np.mean(psd_values[noise_mask])
    
    # calculate SNR
    if noise_avg > 0:
        SNR = ((psd_values[arg_f]) / noise_avg)
    
    # Omit values that does not produce spikes
    else:
        SNR = np.nan
        
    return SNR